import type { CollectionEntry } from "astro:content";

export type ProjectEntry = CollectionEntry<"project">;

export interface ProjectSource {
  platform: "GitHub" | "GitLab" | "Bitbucket" | "Gitea" | "Codeberg" | "Other";
  url_repository: string;
  url_documentation?: string;
  license:
    | "Source-available"
    | "0BSD"
    | "BSD-1-Clause"
    | "BSD-2-Clause"
    | "BSD-3-Clause"
    | "AFL-3.0"
    | "APL-1.0"
    | "Apache-1.1"
    | "Apache-2.0"
    | "APSL-2.0"
    | "Artistic-1.0"
    | "Artistic-2.0"
    | "AAL"
    | "BSL-1.0"
    | "3-clause BSD License"
    | "2-clause BSD License"
    | "1-clause BSD License"
    | "0-clause BSD license"
    | "BSD-3-Clause-LBNL"
    | "BSD-2-Clause-Patent"
    | "Creative Commons"
    | "CERN Open Hardware Licence Version 2 - Permissive"
    | "CERN Open Hardware Licence Version 2 - Weakly Reciprocal"
    | "CERN Open Hardware Licence Version 2 - Strongly Reciprocal"
    | "CECILL-2.1"
    | "CDDL-1.0"
    | "CPAL-1.0"
    | "CPL-1.0"
    | "CATOSL-1.1"
    | "Coopyleft"
    | "CopyFair"
    | "CSL"
    | "CAL-1.0"
    | "EPL-1.0"
    | "EPL-2.0"
    | "eCos-2.0"
    | "ECL-1.0"
    | "ECL-2.0"
    | "EFL-1.0"
    | "EFL-2.0"
    | "Entessa"
    | "EUDatagrid"
    | "EUPL-1.2"
    | "FairSource"
    | "Frameworx-1.0"
    | "AGPL-3.0"
    | "GPL-2.0"
    | "GPL-3.0"
    | "LGPL-2.1"
    | "LGPL-3.0"
    | "HPND"
    | "IPL-1.0"
    | "IPA"
    | "ISC"
    | "Jam"
    | "LPPL-1.3c"
    | "BSD-3-Clause-LBNL"
    | "LiLiQ-P"
    | "LiLiQ-R"
    | "LiLiQ-R+"
    | "LPL-1.0"
    | "LPL-1.02"
    | "MS-PL"
    | "MS-RL"
    | "MirOS"
    | "MIT"
    | "MIT-0"
    | "Motosoto"
    | "MPL-1.0"
    | "MPL-1.1"
    | "MPL-2.0"
    | "MulanPSL"
    | "Multics"
    | "NASA-1.3"
    | "Naumen"
    | "NGPL"
    | "NPOSL-3.0"
    | "NTP"
    | "OCLC-2.0"
    | "OGTSL"
    | "OSL-1.0"
    | "OSL-2.1"
    | "OSL-3.0"
    | "OLDAP-2.8"
    | "QPL-1.0"
    | "RPSL-1.0"
    | "RPL-1.1"
    | "RPL-1.5"
    | "RSCPL"
    | "OFL-1.1"
    | "PPL"
    | "SimPL-2.0"
    | "Sleepycat"
    | "SPL-1.0"
    | "Watcom-1.0"
    | "UPL"
    | "NCSA"
    | "Upstream Compatibility License v1.0"
    | "Unicode Data Files and Software License"
    | "Unlicense"
    | "VSL-1.0"
    | "W3C"
    | "WXwindows"
    | "Xnet"
    | "ZPL-2.0"
    | "ZPL-2.1"
    | "Zlib";
  language:
    | "C"
    | "Bash"
    | "Shell"
    | "HTML"
    | "CSS"
    | "JavaScript"
    | "Java"
    | "Python"
    | "PHP"
    | "C++"
    | "C#"
    | "SQL"
    | "Perl"
    | "Pascal"
    | "Ruby"
    | "Lua"
    | "BASIC"
    | "Fortran"
    | "assembly"
    | "MATLAB"
    | "Lisp"
    | "COBOL"
    | "R"
    | "Ada"
    | "Haskell"
    | "Prolog"
    | "Go"
    | "Scratch"
    | "Visual Basic"
    | "ALGOL"
    | "Kotlin"
    | "Rust"
    | "Swift"
    | "Objective-C"
    | "Scala"
    | "TeX"
    | "TypeScript"
    | "HCL"
    | "Dart"
    | "Elixir"
    | "Erlang"
    | "F#"
    | "Julia"
    | "Elm"
    | "Other";
}

export interface ProjectOwner {
  name: string;
  type: "individual" | "community" | "organization";
  description?: string;
  tags?: string[];
  url_website?: string | null;
  is_a_startup?: boolean;
}

export interface ProjectMetadata {
  filename: string;
  created_at: string;
  [key: string]: unknown;
}

export interface Project {
  name: string;
  description: string;
  tags?: string[];
  category:
    | "app"
    | "saas"
    | "paas"
    | "faas"
    | "package"
    | "library"
    | "learning"
    | "language"
    | "framework"
    | "cli"
    | "api"
    | "scripts"
    | "ai"
    | "awesome-list"
    | "os"
    | "other";
  country:
    | "Italy"
    | "France"
    | "Germany"
    | "Spain"
    | "Poland"
    | "Netherlands"
    | "Belgium"
    | "Sweden"
    | "Austria"
    | "Czech Republic"
    | "Denmark"
    | "Finland"
    | "Greece"
    | "Hungary"
    | "Ireland"
    | "Croatia"
    | "Lithuania"
    | "Latvia"
    | "Slovakia"
    | "Slovenia"
    | "Estonia"
    | "Portugal"
    | "Bulgaria"
    | "Romania"
    | "Luxembourg"
    | "Malta"
    | "Cyprus";
  source: ProjectSource;
  owner: ProjectOwner;
  metadata: ProjectMetadata;
}
